[rally]
output_root = "./rally-to-anything/rally"

[rally.sdk]
api_key = "<API_KEY>"
server = "rally1.rallydev.com"
workspace = "Example Workspace"
project = "Example Project"

[rally.artifacts.features]
entity = "PortfolioItem/Feature"
query = ["State != Done", "State != Removed"]
threads = 4

[rally.artifacts.stories]
entity = "HierarchicalRequirement"
query = ["ScheduleState != Done/Merged", "Feature = null"]
threads = 4

[rally.artifacts.defects]
entity = "Defect"
query = "((State = Open) OR (State = Submitted))"
threads = 4

[clubhouse]
[clubhouse.api]
api_key = "<API_KEY>"

[jira]
[jira.json]
filepath = "./rally-to-anything/jira/rally-to-jira.json"

[jira.sdk]
email = "john@example.com"
api_token = "<API_KEY>"
server = "https://example.atlassian.net"

[jira.project]
key = "EXA"


[jira.mappings.artifacts]
Defect = "Bug"
HierarchicalRequirement = "Sub-task"
PortfolioItem = "Story"
"PortfolioItem/Epic" = "Epic"
Task = "Sub-task"

[jira.mappings.issuelinking]
Defect = "sub-task-link"
Story = "sub-task-link"
Sub-task = "Dependent"

[jira.mappings.priority]
Critical = "Critical"
Urgent = "Urgent"
High = "High"
Normal = "Normal"
Low = "Low"

[jira.mappings.status.issue]
Backlog = "Open"
Review = "Open"
Defined = "Open"
Developing = "In Progress"
"In-Progress" = "In Progress"
"In Progress" = "In Progress"
Measuring = "In Progress"
Complete = "Complete"
Completed = "Complete"
Accepted = "Accepted"
"Done/Merged" = "Done"
Done = "Done"
Removed = "Won't Do"

[jira.mappings.status.epic]
Discovering = "To Do"
Developing = "In Progress"
Measuring = "In Progress"
Done = "Done"

[jira.mappings.status.bug]
Submitted = "Submitted"
Open = "Open"
Closed = "Closed"
"In Progress" = "In Progress"
"Won't Fix" = "Won't Fix"
Duplicate = "Duplicate"
"Not a Defect" = "Rejected"

[jira.mappings.resolution]
Done = "Done"
Duplicate = "Duplicate"
"Won't Fix" = "Won't Do"
Rejected = "Cannot Reproduce"

[jira.mappings.labels]
fields = ["milestones"]

[jira.mappings.customfields.clientNames]
fieldName = "Clients"
fieldType = "com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes"
skip_values = ["None", "No Clients Affected", "All Clients Affected"]

[jira.mappings.customfields.project]
fieldName = "Team"
fieldType = "com.atlassian.jira.plugin.system.customfieldtypes:select"
skip_values = ["Example", "xArchived"]

[jira.mappings.zendesk_import]
fieldName = "(Imported) Zendesk Ticket IDs"
fieldType = "com.atlassian.jira.plugin.system.customfieldtypes:textarea"

[aws]
sso_profile = "jira-migration"
region = "us-east-1"
s3_endpoint_url = "https://s3.us-east-1.amazonaws.com"
bucket_name = "jira-migration"
s3_presign_expires = 600

[zendesk]
[zendesk.sdk]
subdomain = "example"
email = "susan@example.com"
token = "<TOKEN>"
