[rally]
output_root = "./rally-to-anything/rally"

[rally.sdk]
api_key = "<API_KEY>"
server = "rally1.rallydev.com"
workspace = "Example Workspace"
project = "Example Project"

[rally.artifacts.features]
entity = "PortfolioItem/Feature"
query = ["State != Done", "State != Removed"]
threads = 4

[rally.artifacts.defects]
entity = "Defect"
query = "((State = Open) OR (State = Submitted))"
threads = 4

[clubhouse]
[clubhouse.api]
api_key = "<API_KEY>"

[jira]
[jira.sdk]
email = "john@example.com"
api_token = "<API_KEY>"
server = "https://example.atlassian.net"

[jira.artifacts.mappings]
HierarchicalRequirement = "Task"
"PortfolioItem/Feature" = "Story"
"PortfolioItem/Epic" = "Epic"
Task = "Sub-task"
[jira.artifacts.labels]
fields = ["milestones"]
