[rally]
output_root = "./rally-to-anything/rally"

[rally.sdk]
api_key = "<API_KEY>"
server = "rally1.rallydev.com"
workspace = "Example Workspace"
project = "Example Project"

[rally.artifacts.features]
entity = "PortfolioItem/Feature"
query = ["State != Done", "State != Removed"]
threads = 4

[rally.artifacts.defects]
entity = "Defect"
query = "((State = Open) OR (State = Submitted))"
threads = 4

[clubhouse]
[clubhouse.api]
api_key = "<API_KEY>"

[jira]
[jira.sdk]
api_key = "<API_KEY>"
server = "example.atlassian.net"

#[mappings]
#Tags = Label
#HierarchicalRequirement = Story
#PortfolioItem/Feature = Epic
#PortfolioItem/Epic = Milestone
#Task = Task
#TestCase = NULL
#
#{'TestCase', 'PortfolioItem/Feature', 'Task', 'PortfolioItem/Epic', 'HierarchicalRequirement'}
#
#[mappings.labels]
#Foo = "client: Foo"
#__unmapped__ = "__identity__"
#
#[mappings.comments]
