[rally]
output_root = "./rally-to-anything/rally"
[rally.filters]
ignored_projects = ["zArchived.*", "Special Projects"]
skip_migration_tag = "SKIP-MIGRATION"

[rally.sdk]
api_key = "<API_KEY>"
server = "rally1.rallydev.com"
workspace = "Example Workspace"

[clubhouse]
[clubhouse.api]
api_key = "<API_KEY>"

[jira]
[jira.api]
api_key = "<API_KEY>"
server = "example.atlassian.net"

#[mappings]
#Tags = Label
#HierarchicalRequirement = Story
#PortfolioItem/Feature = Epic
#PortfolioItem/Epic = Milestone
#Task = Task
#TestCase = NULL
#
#{'TestCase', 'PortfolioItem/Feature', 'Task', 'PortfolioItem/Epic', 'HierarchicalRequirement'}
#
#[mappings.labels]
#Foo = "client: Foo"
#__unmapped__ = "__identity__"
#
#[mappings.comments]
