[rally]
output_root = "./rally-to-anything/rally"

[rally.sdk]
api_key = "<API_KEY>"
server = "rally1.rallydev.com"
workspace = "Example Workspace"
project = "Example Project"

[rally.artifacts.features]
entity = "PortfolioItem/Feature"
query = ["State != Done", "State != Removed"]
threads = 4

[rally.artifacts.defects]
entity = "Defect"
query = "((State = Open) OR (State = Submitted))"
threads = 4

[clubhouse]
[clubhouse.api]
api_key = "<API_KEY>"

[jira]
[jira.sdk]
email = "john@example.com"
api_token = "<API_KEY>"
server = "https://example.atlassian.net"

[jira.project]
key = "EXA"

[jira.mappings.artifacts]
Defect = "Bug"
HierarchicalRequirement = "Sub-task"
"PortfolioItem" = "Story"
"PortfolioItem/Epic" = "Epic"
Task = "Sub-task"

[jira.mappings.priority]
Critical = "Critical"
Urgent = "Highest"
High = "Medium"
Normal = "Low"
Low = "Lowest"

[jira.mappings.status]
Backlog = "Backlog"
Defined = "Defined"
"Discovery" = "To Do"
"To Do" = "To Do"
"Developing" = "In Progress"
"In-Progress" = "In Progress"
"In Progress" = "In Progress"
"Measuring" = "In Progress"
Complete = "Complete"
Accepted = "Accepted"
"Done" = "Done"
"Done/Merged" = "Done"
Submitted = "Submitted"
Open = "Open"
Closed = "Closed"
"Won't Fix" = "Won't Fix"
"Duplicate" = "Duplicate"
"Not a Defect" = "Rejected"

[jira.mappings.resolution]
Done = "Done"
Duplicate = "Duplicate"
"Won't Fix" = "Won't Do"
Rejected = "Cannot Reproduce"
Accepted = "Accepted"

[jira.mappings.labels]
fields = ["iteration", "release", "milestones"]
